// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Photo2GoAPI.Data;

#nullable disable

namespace Photo2GoAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260406180503_AddRecommendationFeedbackTable")]
    partial class AddRecommendationFeedbackTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Photo2GoAPI.Model.GeneratedRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AnalysisJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("analysis_json");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FileJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_json");

                    b.Property<string>("SimilarLocationsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("similar_locations_json");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GeneratedRoutes");
                });

            modelBuilder.Entity("Photo2GoAPI.Model.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ArchitectureStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuildingMaterials")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("ClosingTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("IsUnescoProtected")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("OpeningTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArchitectureStyle = "Gothic",
                            BuildingMaterials = "Bricks, Stone",
                            Category = "Historical Monument",
                            City = "Vilnius",
                            ClosingTime = new TimeOnly(20, 0, 0),
                            IsUnescoProtected = "Yes",
                            Name = "Gediminas Tower",
                            ObjectType = "Castle",
                            OpeningTime = new TimeOnly(10, 0, 0),
                            Period = "14th century",
                            Province = "Vilnius County"
                        },
                        new
                        {
                            Id = 2,
                            ArchitectureStyle = "Classicism",
                            BuildingMaterials = "Plaster, Bricks",
                            Category = "Religious Object",
                            City = "Vilnius",
                            ClosingTime = new TimeOnly(18, 0, 0),
                            IsUnescoProtected = "Yes",
                            Name = "Vilnius Cathedral",
                            ObjectType = "Church",
                            OpeningTime = new TimeOnly(8, 0, 0),
                            Period = "18th century",
                            Province = "Vilnius County"
                        },
                        new
                        {
                            Id = 3,
                            ArchitectureStyle = "Flamboyant Gothic",
                            BuildingMaterials = "Clay, Bricks",
                            Category = "Religious Object",
                            City = "Vilnius",
                            ClosingTime = new TimeOnly(18, 0, 0),
                            IsUnescoProtected = "Yes",
                            Name = "St. Anne's Church",
                            ObjectType = "Church",
                            OpeningTime = new TimeOnly(9, 0, 0),
                            Period = "15th century",
                            Province = "Vilnius County"
                        },
                        new
                        {
                            Id = 4,
                            ArchitectureStyle = "Baroque/Renaissance",
                            BuildingMaterials = "Masonry",
                            Category = "Educational Institution",
                            City = "Vilnius",
                            ClosingTime = new TimeOnly(20, 0, 0),
                            IsUnescoProtected = "Yes",
                            Name = "Vilnius University",
                            ObjectType = "University",
                            OpeningTime = new TimeOnly(8, 0, 0),
                            Period = "16th century",
                            Province = "Vilnius County"
                        },
                        new
                        {
                            Id = 5,
                            ArchitectureStyle = "Renaissance",
                            BuildingMaterials = "Stone, Bricks",
                            Category = "Religious/Defensive",
                            City = "Vilnius",
                            ClosingTime = new TimeOnly(19, 0, 0),
                            IsUnescoProtected = "Yes",
                            Name = "Gate of Dawn",
                            ObjectType = "City Gate",
                            OpeningTime = new TimeOnly(6, 0, 0),
                            Period = "16th century",
                            Province = "Vilnius County"
                        },
                        new
                        {
                            Id = 6,
                            ArchitectureStyle = "Baroque",
                            BuildingMaterials = "Masonry, Stucco",
                            Category = "Religious Object",
                            City = "Vilnius",
                            ClosingTime = new TimeOnly(18, 0, 0),
                            IsUnescoProtected = "No",
                            Name = "St. Peter and St. Paul's Church",
                            ObjectType = "Church",
                            OpeningTime = new TimeOnly(9, 0, 0),
                            Period = "17th century",
                            Province = "Vilnius County"
                        },
                        new
                        {
                            Id = 7,
                            ArchitectureStyle = "Classicism",
                            BuildingMaterials = "Masonry, Plaster",
                            Category = "Government Building",
                            City = "Vilnius",
                            ClosingTime = new TimeOnly(17, 0, 0),
                            IsUnescoProtected = "Yes",
                            Name = "Presidential Palace",
                            ObjectType = "Palace",
                            OpeningTime = new TimeOnly(9, 0, 0),
                            Period = "19th century",
                            Province = "Vilnius County"
                        },
                        new
                        {
                            Id = 8,
                            ArchitectureStyle = "Classicism",
                            BuildingMaterials = "Masonry",
                            Category = "Local Government",
                            City = "Vilnius",
                            ClosingTime = new TimeOnly(18, 0, 0),
                            IsUnescoProtected = "Yes",
                            Name = "Vilnius Town Hall",
                            ObjectType = "Town Hall",
                            OpeningTime = new TimeOnly(9, 0, 0),
                            Period = "18th century",
                            Province = "Vilnius County"
                        },
                        new
                        {
                            Id = 9,
                            ArchitectureStyle = "None",
                            BuildingMaterials = "Nature",
                            Category = "Recreational Area",
                            City = "Vilnius",
                            ClosingTime = new TimeOnly(22, 0, 0),
                            IsUnescoProtected = "Yes",
                            Name = "Bernardinai Garden",
                            ObjectType = "Park",
                            OpeningTime = new TimeOnly(6, 0, 0),
                            Period = "15th century",
                            Province = "Vilnius County"
                        },
                        new
                        {
                            Id = 10,
                            ArchitectureStyle = "Modernism",
                            BuildingMaterials = "Bronze",
                            Category = "Artistic Object",
                            City = "Vilnius",
                            ClosingTime = new TimeOnly(23, 59, 0),
                            IsUnescoProtected = "Yes",
                            Name = "Angel of Uzupis",
                            ObjectType = "Sculpture",
                            OpeningTime = new TimeOnly(0, 0, 0),
                            Period = "21st century",
                            Province = "Vilnius County"
                        });
                });

            modelBuilder.Entity("Photo2GoAPI.Model.RoutePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("LocationIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("location_ids_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Photo2GoAPI.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Photo2GoAPI.Models.StoredRecommendationFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedCategory")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("DetectedLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetectedObjectType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DetectedLocationId");

                    b.HasIndex("UserId");

                    b.ToTable("RecommendationFeedback");
                });

            modelBuilder.Entity("Photo2GoAPI.Model.GeneratedRoute", b =>
                {
                    b.HasOne("Photo2GoAPI.Model.User", "User")
                        .WithMany("GeneratedRoutes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Photo2GoAPI.Models.StoredRecommendationFeedback", b =>
                {
                    b.HasOne("Photo2GoAPI.Model.Location", "DetectedLocation")
                        .WithMany()
                        .HasForeignKey("DetectedLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Photo2GoAPI.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DetectedLocation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Photo2GoAPI.Model.User", b =>
                {
                    b.Navigation("GeneratedRoutes");
                });
#pragma warning restore 612, 618
        }
    }
}
