// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Photo2GoAPI.Data;

#nullable disable

namespace Photo2GoAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316141903_InitialCreateWithEnglishSeed")]
    partial class InitialCreateWithEnglishSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Photo2GoAPI.Model.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ArchitectureStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuildingMaterials")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IsUnescoProtected")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArchitectureStyle = "Gothic",
                            BuildingMaterials = "Bricks, Stone",
                            Category = "Historical Monument",
                            City = "Vilnius",
                            IsUnescoProtected = "Yes",
                            Name = "Gediminas Tower",
                            ObjectType = "Castle",
                            Period = "14th century",
                            Province = "Vilnius County"
                        },
                        new
                        {
                            Id = 2,
                            ArchitectureStyle = "Classicism",
                            BuildingMaterials = "Plaster, Bricks",
                            Category = "Religious Object",
                            City = "Vilnius",
                            IsUnescoProtected = "Yes",
                            Name = "Vilnius Cathedral",
                            ObjectType = "Church",
                            Period = "18th century",
                            Province = "Vilnius County"
                        },
                        new
                        {
                            Id = 3,
                            ArchitectureStyle = "Flamboyant Gothic",
                            BuildingMaterials = "Clay, Bricks",
                            Category = "Religious Object",
                            City = "Vilnius",
                            IsUnescoProtected = "Yes",
                            Name = "St. Anne's Church",
                            ObjectType = "Church",
                            Period = "15th century",
                            Province = "Vilnius County"
                        },
                        new
                        {
                            Id = 4,
                            ArchitectureStyle = "Baroque/Renaissance",
                            BuildingMaterials = "Masonry",
                            Category = "Educational Institution",
                            City = "Vilnius",
                            IsUnescoProtected = "Yes",
                            Name = "Vilnius University",
                            ObjectType = "University",
                            Period = "16th century",
                            Province = "Vilnius County"
                        },
                        new
                        {
                            Id = 5,
                            ArchitectureStyle = "Renaissance",
                            BuildingMaterials = "Stone, Bricks",
                            Category = "Religious/Defensive",
                            City = "Vilnius",
                            IsUnescoProtected = "Yes",
                            Name = "Gate of Dawn",
                            ObjectType = "City Gate",
                            Period = "16th century",
                            Province = "Vilnius County"
                        },
                        new
                        {
                            Id = 6,
                            ArchitectureStyle = "Baroque",
                            BuildingMaterials = "Masonry, Stucco",
                            Category = "Religious Object",
                            City = "Vilnius",
                            IsUnescoProtected = "No",
                            Name = "St. Peter and St. Paul's Church",
                            ObjectType = "Church",
                            Period = "17th century",
                            Province = "Vilnius County"
                        },
                        new
                        {
                            Id = 7,
                            ArchitectureStyle = "Classicism",
                            BuildingMaterials = "Masonry, Plaster",
                            Category = "Government Building",
                            City = "Vilnius",
                            IsUnescoProtected = "Yes",
                            Name = "Presidential Palace",
                            ObjectType = "Palace",
                            Period = "19th century",
                            Province = "Vilnius County"
                        },
                        new
                        {
                            Id = 8,
                            ArchitectureStyle = "Classicism",
                            BuildingMaterials = "Masonry",
                            Category = "Local Government",
                            City = "Vilnius",
                            IsUnescoProtected = "Yes",
                            Name = "Vilnius Town Hall",
                            ObjectType = "Town Hall",
                            Period = "18th century",
                            Province = "Vilnius County"
                        },
                        new
                        {
                            Id = 9,
                            ArchitectureStyle = "None",
                            BuildingMaterials = "Nature",
                            Category = "Recreational Area",
                            City = "Vilnius",
                            IsUnescoProtected = "Yes",
                            Name = "Bernardinai Garden",
                            ObjectType = "Park",
                            Period = "15th century",
                            Province = "Vilnius County"
                        },
                        new
                        {
                            Id = 10,
                            ArchitectureStyle = "Modernism",
                            BuildingMaterials = "Bronze",
                            Category = "Artistic Object",
                            City = "Vilnius",
                            IsUnescoProtected = "Yes",
                            Name = "Angel of Uzupis",
                            ObjectType = "Sculpture",
                            Period = "21st century",
                            Province = "Vilnius County"
                        });
                });

            modelBuilder.Entity("Photo2GoAPI.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
